# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/ui/initial_prices_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InitialPricesDialog(object):
    def setupUi(self, InitialPricesDialog):
        InitialPricesDialog.setObjectName("InitialPricesDialog")
        InitialPricesDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(InitialPricesDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelInfo = QtWidgets.QLabel(InitialPricesDialog)
        self.labelInfo.setWordWrap(True)
        self.labelInfo.setObjectName("labelInfo")
        self.verticalLayout.addWidget(self.labelInfo)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.labelYear = QtWidgets.QLabel(InitialPricesDialog)
        self.labelYear.setObjectName("labelYear")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelYear)
        self.editYear = QtWidgets.QLineEdit(InitialPricesDialog)
        self.editYear.setObjectName("editYear")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.editYear)
        self.labelClubPrice = QtWidgets.QLabel(InitialPricesDialog)
        self.labelClubPrice.setObjectName("labelClubPrice")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelClubPrice)
        self.editClubPrice = QtWidgets.QLineEdit(InitialPricesDialog)
        self.editClubPrice.setObjectName("editClubPrice")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.editClubPrice)
        self.labelMJCPrice = QtWidgets.QLabel(InitialPricesDialog)
        self.labelMJCPrice.setObjectName("labelMJCPrice")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelMJCPrice)
        self.editMJCPrice = QtWidgets.QLineEdit(InitialPricesDialog)
        self.editMJCPrice.setObjectName("editMJCPrice")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.editMJCPrice)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(InitialPricesDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(InitialPricesDialog)
        self.buttonBox.accepted.connect(InitialPricesDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(InitialPricesDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(InitialPricesDialog)

    def retranslateUi(self, InitialPricesDialog):
        _translate = QtCore.QCoreApplication.translate
        InitialPricesDialog.setWindowTitle(_translate("InitialPricesDialog", "Configuration des tarifs"))
        self.labelInfo.setText(_translate("InitialPricesDialog", "Veuillez configurer les tarifs pour cette nouvelle base de données.\n"
"Ces tarifs seront appliqués par défaut pour tous les membres."))
        self.labelYear.setText(_translate("InitialPricesDialog", "Année :"))
        self.editYear.setPlaceholderText(_translate("InitialPricesDialog", "ex: 2024-2025"))
        self.labelClubPrice.setText(_translate("InitialPricesDialog", "Prix Club (€) :"))
        self.editClubPrice.setPlaceholderText(_translate("InitialPricesDialog", "0.00"))
        self.labelMJCPrice.setText(_translate("InitialPricesDialog", "Prix MJC (€) :"))
        self.editMJCPrice.setPlaceholderText(_translate("InitialPricesDialog", "0.00"))
