# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/ui/mailing_tab.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MailingTab(object):
    def setupUi(self, MailingTab):
        MailingTab.setObjectName("MailingTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(MailingTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayoutTop = QtWidgets.QHBoxLayout()
        self.horizontalLayoutTop.setObjectName("horizontalLayoutTop")
        self.buttonSendMail = QtWidgets.QPushButton(MailingTab)
        self.buttonSendMail.setObjectName("buttonSendMail")
        self.horizontalLayoutTop.addWidget(self.buttonSendMail)
        self.buttonPreviewMail = QtWidgets.QPushButton(MailingTab)
        self.buttonPreviewMail.setObjectName("buttonPreviewMail")
        self.horizontalLayoutTop.addWidget(self.buttonPreviewMail)
        self.buttonSelectRecipients = QtWidgets.QPushButton(MailingTab)
        self.buttonSelectRecipients.setObjectName("buttonSelectRecipients")
        self.horizontalLayoutTop.addWidget(self.buttonSelectRecipients)
        self.verticalLayout.addLayout(self.horizontalLayoutTop)
        self.horizontalLayoutSubject = QtWidgets.QHBoxLayout()
        self.horizontalLayoutSubject.setObjectName("horizontalLayoutSubject")
        self.labelSubject = QtWidgets.QLabel(MailingTab)
        self.labelSubject.setObjectName("labelSubject")
        self.horizontalLayoutSubject.addWidget(self.labelSubject)
        self.editSubject = QtWidgets.QLineEdit(MailingTab)
        self.editSubject.setObjectName("editSubject")
        self.horizontalLayoutSubject.addWidget(self.editSubject)
        self.verticalLayout.addLayout(self.horizontalLayoutSubject)
        self.editBody = QtWidgets.QTextEdit(MailingTab)
        self.editBody.setObjectName("editBody")
        self.verticalLayout.addWidget(self.editBody)

        self.retranslateUi(MailingTab)
        QtCore.QMetaObject.connectSlotsByName(MailingTab)

    def retranslateUi(self, MailingTab):
        _translate = QtCore.QCoreApplication.translate
        self.buttonSendMail.setText(_translate("MailingTab", "Envoyer"))
        self.buttonPreviewMail.setText(_translate("MailingTab", "Prévisualiser"))
        self.buttonSelectRecipients.setText(_translate("MailingTab", "Sélection destinataires"))
        self.labelSubject.setText(_translate("MailingTab", "Objet :"))
        self.editSubject.setPlaceholderText(_translate("MailingTab", "Saisissez l\'objet du mail..."))
        self.editBody.setPlaceholderText(_translate("MailingTab", "Rédigez votre message ici..."))
