# -*- coding: utf-8 -*-
"""
Fichier généré par pyuic5 à partir de resources/ui/member_form_dialog.ui
Classe : Ui_MemberFormDialog
"""

from PyQt5 import QtWidgets, QtCore

class Ui_MemberFormDialog(object):
    def setupUi(self, MemberFormDialog):
        MemberFormDialog.setObjectName("MemberFormDialog")
        MemberFormDialog.resize(600, 700)
        self.verticalLayout = QtWidgets.QVBoxLayout(MemberFormDialog)
        self.formLayout = QtWidgets.QFormLayout()
        self.editLastName = QtWidgets.QLineEdit(MemberFormDialog)
        self.formLayout.addRow("Nom :", self.editLastName)
        self.editFirstName = QtWidgets.QLineEdit(MemberFormDialog)
        self.formLayout.addRow("Prénom :", self.editFirstName)
        self.editAddress = QtWidgets.QLineEdit(MemberFormDialog)
        self.formLayout.addRow("Adresse :", self.editAddress)
        self.editPostalCode = QtWidgets.QLineEdit(MemberFormDialog)
        self.formLayout.addRow("Code postal :", self.editPostalCode)
        self.editCity = QtWidgets.QLineEdit(MemberFormDialog)
        self.formLayout.addRow("Ville :", self.editCity)
        self.editPhone = QtWidgets.QLineEdit(MemberFormDialog)
        self.formLayout.addRow("N° de tél. :", self.editPhone)
        self.editMail = QtWidgets.QLineEdit(MemberFormDialog)
        self.formLayout.addRow("Mail :", self.editMail)
        self.checkRGPD = QtWidgets.QCheckBox(MemberFormDialog)
        self.checkRGPD.setText("Consentement RGPD (obligatoire)")
        self.formLayout.addRow(self.checkRGPD)
        self.checkImageRights = QtWidgets.QCheckBox(MemberFormDialog)
        self.checkImageRights.setText("Droit à l'image accepté")
        self.formLayout.addRow(self.checkImageRights)
        self.editHealth = QtWidgets.QLineEdit(MemberFormDialog)
        self.formLayout.addRow("Fiche santé :", self.editHealth)
        self.checkANCV = QtWidgets.QCheckBox(MemberFormDialog)
        self.checkANCV.setText("Paiement ANCV")
        self.formLayout.addRow(self.checkANCV)
        self.editCash = QtWidgets.QLineEdit(MemberFormDialog)
        self.formLayout.addRow("Espèce :", self.editCash)
        self.editCheque1 = QtWidgets.QLineEdit(MemberFormDialog)
        self.formLayout.addRow("Chèque 1 :", self.editCheque1)
        self.editCheque2 = QtWidgets.QLineEdit(MemberFormDialog)
        self.formLayout.addRow("Chèque 2 :", self.editCheque2)
        self.editCheque3 = QtWidgets.QLineEdit(MemberFormDialog)
        self.formLayout.addRow("Chèque 3 :", self.editCheque3)
        self.editTotalPaid = QtWidgets.QLineEdit(MemberFormDialog)
        self.formLayout.addRow("Total payé :", self.editTotalPaid)
        self.editClubPart = QtWidgets.QLineEdit(MemberFormDialog)
        self.formLayout.addRow("Part adhésion club :", self.editClubPart)
        self.editMJCPart = QtWidgets.QLineEdit(MemberFormDialog)
        self.formLayout.addRow("Part adhésion MJC :", self.editMJCPart)
        self.checkMultiClub = QtWidgets.QCheckBox(MemberFormDialog)
        self.checkMultiClub.setText("Déjà membre d'un autre club")
        self.formLayout.addRow(self.checkMultiClub)
        self.editExternalClub = QtWidgets.QLineEdit(MemberFormDialog)
        self.editExternalClub.setPlaceholderText("Nom du club externe")
        self.editExternalClub.setEnabled(False)
        self.formLayout.addRow("Club externe :", self.editExternalClub)
        self.checkMJCElsewhere = QtWidgets.QCheckBox(MemberFormDialog)
        self.checkMJCElsewhere.setText("Part MJC déjà réglée ailleurs")
        self.formLayout.addRow(self.checkMJCElsewhere)
        self.editMJCClub = QtWidgets.QLineEdit(MemberFormDialog)
        self.editMJCClub.setPlaceholderText("Nom du club où la part MJC a été réglée")
        self.editMJCClub.setEnabled(False)
        self.formLayout.addRow("Club MJC réglé :", self.editMJCClub)
        self.buttonBox = QtWidgets.QDialogButtonBox(MemberFormDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.verticalLayout.addLayout(self.formLayout)
        self.verticalLayout.addWidget(self.buttonBox)