name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Clean pre-installed packages
        run: |
          pip uninstall -y numpy || true
          pip install --upgrade pip setuptools wheel

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Install dependencies
        run: pip install --upgrade -r requirements.txt

      - name: Run tests
        run: pytest -vv --maxfail=1
