name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libatlas-base-dev

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip and build tools
        run: pip install --upgrade pip setuptools wheel

      - name: Install numpy separately
        run: pip install numpy>=1.23

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Install dependencies
        run: pip install --upgrade -r requirements.txt

      - name: Show package versions
        run: pip freeze

      - name: Run tests
        run: pytest -v --maxfail=1
